dairy/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
app_name = 'dairy'

urlpatterns = [
	path('', views.homePage, name='home'),
	path('milklist/', views.milkList, name='milklist'),
	path('addmilk/', views.addMilk, name='addmilk'),
	path('search/', views.searchFilter, name='search'),
	path('logout/', views.logoutView, name='logout'),
	path('login/',LoginView.as_view(template_name='login.html'), name='login'),
]

dairysystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dairy.urls', namespace='dairy')),

]

dairy/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class dairyNode(models.Model):
	Name 		=	models.ForeignKey(User, on_delete= models.CASCADE)
	Quantity_of_milk = models.FloatField()
	Date		=	models.DateTimeField(auto_now_add=True)
	Person_Name = 	models.CharField(max_length=15)

	def __str__(self):
		return self.Name.username

dairy/forms.py
from django import forms
from .models import dairyNode


class dairyForm(forms.ModelForm):
	class Meta:
		model = dairyNode
		fields = ['Quantity_of_milk', 'Person_Name']

class searchForm(forms.Form):
	search_by_day = forms.BooleanField(required=False)
	Date = forms.DateField(widget=forms.SelectDateWidget(), required=False)
	Node = forms.CharField(required=False)

dairy/views.py
from django.shortcuts import render, redirect
from .models import dairyNode
from  django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import dairyForm,searchForm
from django.contrib.auth import logout, login
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test, login_required
# Create your views here.
def homePage(request):
	return render(request, 'homepage.html')

@login_required
def milkList(request):
	if request.user.is_superuser:
		milks = dairyNode.objects.all().order_by('-Date')
	else:
		milks = dairyNode.objects.filter(Name__username=request.user).order_by('-Date')
	page = request.GET.get('page')
	paginator = Paginator(milks, 6)
	try:
		milkss = paginator.get_page(page)
	except PageNotAnInteger:
		milkss = paginator.get_page(1)
	except EmptyPage:
		milkss = paginator.get_page(paginator.numbers)
	context = {'milk':milkss}
	return render(request, 'milklist.html',context)

@login_required
def addMilk(request):
	if request.method == 'POST':
		form = dairyForm(request.POST)
		if form.is_valid():
			milk = form.save(commit=False)
			milk.Name = request.user
			milk.save()
			return redirect('dairy:milklist')
	else:
		form = dairyForm()
	return render(request, 'addmilk.html', {'form':form})

@login_required
def searchFilter(request):
	if request.method == 'POST':
		form = searchForm(request.POST)
		if form.is_valid():
			selected_date = form.cleaned_data['Date']
			selected_node = form.cleaned_data['Node']
			searchByday = 	form.cleaned_data['search_by_day']
			if selected_node is not "" and searchByday is True:
				milks = dairyNode.objects.filter(Date__year=selected_date.year,Date__month=selected_date.month,Date__day=selected_date.day).filter(Name__username__icontains=selected_node).order_by('-Date')
			elif selected_node is "" and searchByday is True:
				milks = dairyNode.objects.filter(Date__year=selected_date.year,Date__month=selected_date.month,Date__day=selected_date.day).order_by('-Date')
			elif selected_node is not "" and searchByday is False:
				milks = dairyNode.objects.filter(Name__username__icontains=selected_node).order_by('-Date')
			# page = request.GET.get('page')
			# paginator = Paginator(milks, 6)
			# try:
			# 	milkss = paginator.get_page(page)
			# except PageNotAnInteger:
			# 	milkss = paginator.get_page(1)
			# except EmptyPage:
			# 	milkss = paginator.get_page(paginator.numbers)
			context ={'milk':milks}
			return render(request,'searchlist.html',context)
	else:
		form = searchForm()
	return render(request, 'searchform.html', {'form':form})

def logoutView(request):
	logout(request)
	return HttpResponseRedirect(reverse('dairy:home'))

dairy/templates/addmilk.html
{% extends 'homepage.html' %}
{% load bootstrap4 %}
{% load static %}
{% block additionalstyles%}
<link rel="stylesheet" type="text/css" href="{% static "styles1.css" %}">
{% endblock %}
{% block content%}

<div class="container">
	 <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" style="color:white;">Update Milk </li>
      </ol>
		<form method="POST" enctype="multipart/form-data" class="form">
			{% csrf_token %}
			{%  bootstrap_form form %}
			{% buttons %}
        		<button type="submit" class="btn btn-success">Save</button>
    		{% endbuttons %}
		</form>
	
	
</div>
	

{% endblock %}

dairy/templates/homepage.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block additionalstyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    {% endblock %}
    <title>Dairy System</title>
  </head>
  <body>
  	 <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
    <a class="navbar-brand" href="#">
          <img src="http://placehold.it/150x50?text=Dairy System" alt="">
        </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dairy:home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
        </li>
        </li>
        {% if request.user.is_superuser %}
        
        <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        {{ user.username }}
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'dairy:milklist' %}">View Storgae</a>
        <a class="dropdown-item" href="{% url 'dairy:search' %}">Filter</a>
        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
        <a class="dropdown-item" href="{% url 'dairy:logout' %}">Logout</a>
      </div>
    </li>
    {% else %}
    {% if user.is_authenticated %}
        <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        {{ user.username }}
      </a>
      <div class="dropdown-menu">
        
        <a class="dropdown-item" href="{% url 'dairy:addmilk' %}">Update Storage</a>
        <a class="dropdown-item" href="{% url 'dairy:milklist' %}">View Storgae</a>

        <a class="dropdown-item" href="{% url 'dairy:logout' %}">Logout</a>
      </div>
    </li>
    {% else %}
    <a class="nav-link" href="{% url 'dairy:login' %}">Login
                <span class="sr-only">(current)</span>
              </a>
    {% endif %}
    {% endif %}
      </ul>
    
    
    </div>
  </div>
</nav>
      {% block content %}
  	<div class="container">
           <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" style="color:white;">Dairy System</li>
      </ol>
      <div class="one">
      <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="one">
      <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
  	</div>
  	{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

dairy/templates/login.html
{% extends 'homepage.html' %}
{% load bootstrap4 %}
{% load static %}
{% block additionalstyles%}
<link rel="stylesheet" type="text/css" href="{% static "styles1.css" %}">
{% endblock %}
{% block content%}

<div class="container">
	 <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" style="color:white;">Login </li>
      </ol>
		<form method="POST" enctype="multipart/form-data" class="form">
			{% csrf_token %}
			{%  bootstrap_form form %}
			
			{% buttons %}
        		<button type="submit" class="btn btn-success">Login</button>
    		{% endbuttons %}
    		<input type="hidden" name="next" value="{% url 'dairy:home' %}">
		</form>
	
	
</div>
	

{% endblock %}

dairy/templates/milklist.html
{% extends 'homepage.html' %}
{% load static %}
{% block additionalstyles%}
<link rel="stylesheet" type="text/css" href="{% static "styles1.css" %}">
{% endblock %}
{% block content%}
<div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" style="color:white;">Dairy list</li>
      </ol>

        <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
          <th class="umesh">Name</th>
          <th>Quantity in litres</th>
          <th>Date</th>
          <th>Person</th>
         
        </tr>
      </thead>
      <tbody>
        {% for milks in milk %}
          <tr>
            <td>
              {{ milks.Name }}
            </td>
            <td class="align-middle">{{ milks.Quantity_of_milk}}</td>
            <td class="align-middle">{{ milks.Date}}</td>
            <td class="align-middle">{{ milks.Person_Name}}</td>
            
          </tr>
        {% endfor %}
      </tbody>
    </table>


<nav aria-label="Page navigation example">
<ul class="pagination">
        {% if milk.has_previous %}
        
        <li class="page-item"><a class="page-link" href="?page={{ milk.previous_page_number }}">&laquo;</a></li>
        {% endif %}
        {% for i in milk.paginator.page_range %}
      {% if milk.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    	{% endfor %}
     

        {% if milk.has_next %}
           <li class="page-item"> <a class="page-link" href="?page={{ milk.next_page_number }}">&raquo;</a></li>
            {% endif %}
</ul>
</nav>


 
</div>
{% endblock %}

dairy/templates/searchform.html
{% extends 'homepage.html' %}
{% load bootstrap4 %}
{% load static %}
{% block additionalstyles%}
<link rel="stylesheet" type="text/css" href="{% static "styles1.css" %}">
{% endblock %}
{% block content%}

<div class="container">
	 <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" style="color:white;">Search by filter </li>
      </ol>
		<form method="POST" enctype="multipart/form-data" class="form">
			{% csrf_token %}
			{%  bootstrap_form form %}
			{% buttons %}
        		<button type="submit" class="btn btn-success">Search</button>
    		{% endbuttons %}
		</form>
	
	
</div>
	

{% endblock %}

dairy/templates/searchlist.html
{% extends 'homepage.html' %}
{% load static %}
{% block additionalstyles%}
<link rel="stylesheet" type="text/css" href="{% static "styles1.css" %}">
{% endblock %}
{% block content%}
<div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" style="color:white;">Dairy list</li>
      </ol>
      {% if milk %}
        <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
          <th class="umesh">Name</th>
          <th>Quantity in litres</th>
          <th>Date</th>
          <th>Person</th>
         
        </tr>
      </thead>
      <tbody>
        {% for milks in milk %}
          <tr>
            <td>
              {{ milks.Name }}
            </td>
            <td class="align-middle">{{ milks.Quantity_of_milk}}</td>
            <td class="align-middle">{{ milks.Date}}</td>
            <td class="align-middle">{{ milks.Person_Name}}</td>
            
          </tr>
        {% endfor %}
      </tbody>
    </table>




{% else %}
 <h4>No list Found</h4>
 {% endif %}
</div>
{% endblock %}